# Generated by Django 3.2.9 on 2021-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_list',
            name='adress',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='data_list',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data_list',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data_list',
            name='family',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='data_list',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
